
name: power_house_billing_app
description: Flutter invoice app with local SQLite CRUD and PDF export/print
publish_to: 'none'

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  path_provider: ^2.1.5
  path: ^1.9.0
  intl: ^0.19.0
  pdf: ^3.11.1
  printing: ^5.13.4

flutter:
  uses-material-design: true
